domain: "###ZARF_VAR_DOMAIN###"

objectStorage:
  secure: true
  accessKey: ""
  secretKey: ""
  bucket: "mattermost"
  endpoint: "s3.amazonaws.com"
  region: "us-west-1"

postgres:
  username: "mattermost.mattermost"
  # Note: Specifying password as anything other than "" will not use the existingSecret
  password: ""
  existingSecret:
    name: "mattermost.mattermost.pg-cluster.credentials.postgresql.acid.zalan.do"
    passwordKey: password
    usernameKey: username
  host: "pg-cluster.postgres.svc.cluster.local"
  dbName: "mattermost"
  # Example: "?connect_timeout=10&sslmode=disable"
  connectionOptions: ""
  # Set to false to use external postgres
  internal: true
  selector:
    cluster-name: pg-cluster
  namespace: postgres
  port: 5432
mattermostLicense: ""
sso:
  enabled: true
  # Options: "gitlab", "openid-connect"
  protocol: "gitlab"
  secretName: mattermost-sso

  # These should typically be disabled if SSO is enabled
  enable_sign_up_with_email: false
  enable_sign_in_with_email: false
  enable_sign_in_with_username: false

  # Config for OIDC/SAML
  login_button_text: "Login with SSO"
  login_button_color: "#144A8F"

# The subdomain for the mattermost server, will be prefixed to your domain (ex: mattermost.example.com)
subdomain: "chat"

# Additional configuration for Mattermost
config:
  enablePluginUploads: false

# Additional environment variables for Mattermost
extraEnv: {}

storage:
  # Set to false to use external storage
  internal: true
  selector:
    app: minio
  namespace: dev-minio
  port: 9000

# custom:
#    # Notice no `remoteGenerated` field here on custom internal rule
#   - direction: Ingress
#     selector:
#       app: jenkins
#     remoteNamespace: jenkins
#     remoteSelector:
#       app: jenkins
#     port: 8180
#     description: "Ingress from Jenkins"
#   # No `remoteNamespace`, `remoteSelector`, or `port` fields on rule to `remoteGenerated`
#   - direction: Egress
#     selector:
#       app: webservice
#     remoteGenerated: Anywhere
#     description: "Egress from Mattermost"
