objectStorage:
  secure: true
  accessKey: ""
  secretKey: ""
  bucket: "mattermost"
  endpoint: "s3.amazonaws.com"
  region: "us-west-1"

postgres:
  username: "mattermost"
  password: ""
  host: ""
  port: 5432
  dbName: "mattermost"
  # Example: "?connect_timeout=10&sslmode=disable"
  connectionOptions: ""

sso:
  enabled: true
  #TODO: ewyles -- need to pick which style of url we want to use. Both work, redirect ones (commented out) don't seem to be necessary
  #auth_endpoint: "https://sso.###ZARF_VAR_DOMAIN###/oauth/authorize"
  #token_endpoint: "https://sso.###ZARF_VAR_DOMAIN###/oauth/token"
  #user_api_endpoint: "https://sso.###ZARF_VAR_DOMAIN###/api/v4/user"
  auth_endpoint: "https://sso.###ZARF_VAR_DOMAIN###/realms/uds/protocol/openid-connect/auth"
  token_endpoint: "https://sso.###ZARF_VAR_DOMAIN###/realms/uds/protocol/openid-connect/token"
  user_api_endpoint: "https://sso.###ZARF_VAR_DOMAIN###/realms/uds/protocol/openid-connect/userinfo"

  # These should typically be disabled if SSO is enabled
  enable_sign_up_with_email: false
  enable_sign_in_with_email: false
  enable_sign_in_with_username: false

# The subdomain for the mattermost server, will be prefixed to your domain (ex: mattermost.example.com)
subdomain: "chat"

# Additional configuration for Mattermost
config:
  enablePluginUploads: false

# Additional environment variables for Mattermost
extraEnv: {}
