# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

minio:
  enabled: false
mysqlha:
  enabled: false
mattermostApp:
  # Default replicacount due to HA requiring a license
  replicaCount: 1
  # Mattermost does not provide helm values to configure all the options so it is done via ENV
  envFrom:
    # SSO Settings
    - secretRef:
        name: mattermost-sso
    # Object Storage Connection
    - secretRef:
        name: mattermost-object-store
    # Database Configuration
    - secretRef:
        name: mattermost-postgres
    # General Configuration
    - secretRef:
        name: mattermost-config
    # Extra Configuration
    - secretRef:
        name: mattermost-extra-env
  securityContext:
    runAsUser: 2000
    runAsGroup: 2000

serviceAccount:
  create: true
  name: mattermost
  annotations: {}

global:
  siteUrl: "https://###ZARF_VAR_SUBDOMAIN###.###ZARF_VAR_DOMAIN###"
  # Default unlicensed deployment
  mattermostLicense: "###ZARF_VAR_MM_LICENSE###"

  features:
    database:
      useInternal: false
      existingDatabaseSecret:
        name: mattermost-postgres
        key: MM_SQLSETTINGS_DATASOURCE
    # The job server is only necessary on multi-node/enterprise clusters
    # https://docs.mattermost.com/scale/high-availability-cluster.html#job-server
    # It also will error due to its init container being blocked by Istio mTLS
    jobserver:
      enabled: false
