minio:
  enabled: false
mysqlha:
  enabled: false
# TODO @marshall007: this should work pending: https://github.com/chainguard-images/images/issues/923#issuecomment-2181155300
# initContainerImage:
#   repository: cgr.dev/chainguard/curl
#   tag: latest
mattermostApp:
  # Default replicacount due to HA requiring a license
  replicaCount: 1
  # Mattermost does not provide helm values to configure all the options so it is done via ENV
  envFrom:
    # SSO Settings
    - secretRef:
        name: mattermost-sso
    # Object Storage Connection
    - secretRef:
        name: mattermost-object-store
    # Database Configuration
    - secretRef:
        name: mattermost-postgres
    # General Configuration
    - secretRef:
        name: mattermost-config
    # Extra Configuration
    - secretRef:
        name: mattermost-extra-env
  securityContext:
    runAsUser: 2000
    runAsGroup: 2000
  # extraInitContainers:
  #   # Extra Container to install plugins
  #   - name: mattermost-extra-plugins
  #     image: uds-package-mattermost/mattermost-extra-plugins:latest
  #     imagePullPolicy: Always
  #     volumeMounts:
  #       # Must match plugins volumes from chart

  #       # In mattermost-team-edition chart, this is `/mattermost/$MM_PLUGINSETTINGS_CLIENTDIRECTORY`
  #       # see: https://github.com/mattermost/mattermost-helm/blob/master/charts/mattermost-team-edition/templates/deployment.yaml#L103-L104

  #       # In mattermost-enterprise-edition chart, it is hardcoded to `/mattermost/plugins/`
  #       # see: https://github.com/mattermost/mattermost-helm/blob/master/charts/mattermost-enterprise-edition/templates/deployment-mattermost-app.yaml#L174-L177

  #       # TODO @marshall007: only mattermost-team-edition chart supports plugin persistence. `emptyDir` may cause problems on EE, will need to investigate
  #       # see: https://github.com/mattermost/mattermost-helm/blob/master/charts/mattermost-team-edition/templates/deployment.yaml#L123-L133
  #       - name: mattermost-plugins
  #         mountPath: /mattermost/plugins/

serviceAccount:
  create: true
  name: mattermost
  annotations: {}

global:
  siteUrl: "https://###ZARF_VAR_SUBDOMAIN###.###ZARF_VAR_DOMAIN###"
  # Default unlicensed deployment
  mattermostLicense: ""

  features:
    database:
      useInternal: false
      existingDatabaseSecret:
        name: mattermost-postgres
        key: MM_SQLSETTINGS_DATASOURCE
    # The job server is only necessary on multi-node/enterprise clusters
    # https://docs.mattermost.com/scale/high-availability-cluster.html#job-server
    # It also will error due to its init container being blocked by Istio mTLS
    jobserver:
      enabled: false
