apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: mattermost-sso
  namespace: {{ .Release.Namespace }}
spec:
  sso:
    - name: Mattermost Client
      clientId: mattermost-client
      redirectUris:
        - "https://chat.uds.dev/*"
      defaultClientScopes:
        - "openid"
        - "mapper-oidc-username-username"
        - "mapper-oidc-mattermostid-id"
        - "mapper-oidc-email-email" 

      secretName: mattermost-sso
      secretTemplate:
        MM_GITLABSETTINGS_ENABLE: "{{ .Values.sso.enabled | toString }}"
        MM_GITLABSETTINGS_ID: "clientField(clientId)"
        MM_GITLABSETTINGS_SECRET: "clientField(secret)"
        MM_GITLABSETTINGS_AUTHENDPOINT: "{{ .Values.sso.auth_endpoint }}"
        MM_GITLABSETTINGS_TOKENENDPOINT: "{{ .Values.sso.token_endpoint }}"
        MM_GITLABSETTINGS_USERAPIENDPOINT: "{{ .Values.sso.user_api_endpoint }}"
        MM_EMAILSETTINGS_ENABLESIGNUPWITHEMAIL: "{{ .Values.sso.enable_sign_up_with_email | toString }}"
        MM_EMAILSETTINGS_ENABLESIGNINWITHEMAIL: "{{ .Values.sso.enable_sign_in_with_email | toString }}"
        MM_EMAILSETTINGS_ENABLESIGNINWITHUSERNAME: "{{ .Values.sso.enable_sign_in_with_username | toString }}"
