apiVersion: v1
kind: Secret
metadata:
  name: mattermost-object-store
  namespace: {{.Release.Namespace}}
type: Opaque
stringData:
  MM_FILESETTINGS_AMAZONS3SSL: "{{ .Values.objectStorage.secure | toString }}"
  MM_FILESETTINGS_AMAZONS3ACCESSKEYID: "{{ .Values.objectStorage.accessKey }}"
  MM_FILESETTINGS_AMAZONS3SECRETACCESSKEY: "{{ .Values.objectStorage.secretKey }}"
  MM_FILESETTINGS_AMAZONS3BUCKET: "{{ .Values.objectStorage.bucket }}"
  MM_FILESETTINGS_AMAZONS3ENDPOINT: "{{ .Values.objectStorage.endpoint }}"
  MM_FILESETTINGS_AMAZONS3REGION: "{{ .Values.objectStorage.region }}"
