# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: v1
kind: Secret
metadata:
  name: mattermost-object-store
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:

  {{- $awsAccessKey := "" }}
  {{- $awsSecretKey := "" }}

  {{- $secret := lookup "v1" "Secret" .Values.objectStorage.secretRef.secretNamespace .Values.objectStorage.secretRef.secretName }}
  {{- if and $secret (index $secret.data .Values.objectStorage.secretRef.secretIDKey) }}
    {{- $awsAccessKey = (index $secret.data .Values.objectStorage.secretRef.secretIDKey | b64dec) }}
  {{- else }}
    {{- $awsAccessKey = .Values.objectStorage.accessKey | quote }}
  {{- end }}
  
  {{- if and $secret (index $secret.data .Values.objectStorage.secretRef.secretPasswordKey) }}
    {{- $awsSecretKey = (index $secret.data .Values.objectStorage.secretRef.secretPasswordKey | b64dec) }}
  {{- else }}
    {{- $awsSecretKey = .Values.objectStorage.secretKey | quote }}
  {{- end }}
  MM_FILESETTINGS_DRIVERNAME: amazons3
  MM_FILESETTINGS_AMAZONS3SSL: "{{ .Values.objectStorage.secure | toString }}"
  MM_FILESETTINGS_AMAZONS3ACCESSKEYID: {{ $awsAccessKey }}
  MM_FILESETTINGS_AMAZONS3SECRETACCESSKEY: {{ $awsSecretKey }}
  MM_FILESETTINGS_AMAZONS3BUCKET: "{{ .Values.objectStorage.bucket }}"
  MM_FILESETTINGS_AMAZONS3ENDPOINT: "{{ .Values.objectStorage.endpoint }}"
  MM_FILESETTINGS_AMAZONS3REGION: "{{ .Values.objectStorage.region }}"
