# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

{{- if .Values.rtcService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mattermost-rtc
  namespace: {{ .Release.Namespace }}
{{- with .Values.rtcService }}
  annotations:
    {{- .annotations | toYaml | nindent 4 }}
spec:
  ports:
    {{- .ports | toYaml | nindent 4 }}
  selector:
    app.kubernetes.io/name: mattermost-enterprise-edition
  type: {{ .type }}
{{- end }}
{{- end }}
