# This secret will be used if sso is disabled, instead of the templated one in uds-package.yaml.
# Mattermost needs to mount the secret and creating it this way avoids creating an unnecessary
# client in the keycloak realm and unnecessary secret data in the cluster.
{{- if not .Values.sso.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sso.secretName }}
  namespace:  {{ .Release.Namespace }}
type: "Opaque"
stringData:
  MM_GITLABSETTINGS_ENABLE: "{{ .Values.sso.enabled | toString }}"

{{- end }}
