apiVersion: v1
kind: Secret
metadata:
  name: mattermost-postgres
  namespace: {{.Release.Namespace}}
type: Opaque
stringData:
  db_connection_string: "postgres://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.dbName }}{{ .Values.postgres.connectionOptions }}"
