apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: mattermost
  namespace: {{ .Release.Namespace }}
spec:
  network:
    expose:
      - service: mattermost-enterprise-edition
        podLabels:
          app.kubernetes.io/name: mattermost-enterprise-edition
        gateway: tenant
        host: {{ .Values.host }}
        port: 8065
    allow:
      # Permit intra-namespace communication for job communications
      - direction: Ingress
        remoteGenerated: IntraNamespace

      - direction: Egress
        remoteGenerated: IntraNamespace

      # Todo: wide open for hitting in-cluster or external postgres/s3
      - direction: Egress
        podLabels:
          app.kubernetes.io/name: mattermost-enterprise-edition
        remoteGenerated: Anywhere
