includes:
- deploy: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.4.5/tasks/deploy.yaml
- setup: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.4.5/tasks/setup.yaml

tasks:
  - name: setup
    description: Creates a test cluster, deploys test bundle, and creates a test user
    actions:
      - task: setup:k3d-test-cluster
      - task: deploy:test-bundle
      - task: setup:create-doug-user
