tasks:
  - name: create
    description: Create the Dependency Zarf Package
    actions:
      - cmd: uds zarf package create src/dev-secrets/ --confirm --no-progress --architecture=${UDS_ARCH}
      - cmd: uds zarf package create src/namespace/ --confirm --no-progress --architecture=${UDS_ARCH}
