includes:
  - dependencies: ./dependencies.yaml
  - test: ./test.yaml
  - create: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.4.5/tasks/create.yaml
  - deploy: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.4.5/tasks/deploy.yaml
#  - publish: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.4.5/tasks/publish.yaml
#  - publish: ../../uds-common/tasks/publish.yaml
  - setup: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.4.5/tasks/setup.yaml

tasks:
  - name: package
    description: Build and publish the packages

    actions:
      - task: create:package
      - task: dependencies:create
      - task: create:test-bundle
      - task: setup:k3d-test-cluster
      - task: deploy:test-bundle
      - task: setup:create-doug-user
      - task: test:all

      # - description: Publish the package
      #   task: publish:package
      #   with:
      #     # x-release-please-start-version
      #     version: "9.8.0-uds.0"
      #     # x-release-please-end
