includes:
  - create: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.4.5/tasks/create.yaml
  - publish: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.4.5/tasks/publish.yaml
  - setup: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.4.5/tasks/setup.yaml
  - deploy: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.4.5/tasks/deploy.yaml
  - dependencies: ./dependencies.yaml
  - test: ./test.yaml

tasks:
  - name: package
    description: Build and publish the packages
    actions:
      - description: Publish the packages
        task: publish:package
        with:
          # x-release-please-start-version
          version: "9.8.0-uds.0"
          # x-release-please-end
