includes:
  - dependencies: ./dependencies.yaml
  - test: ./test.yaml
  - create: https://raw.githubusercontent.com/defenseunicorns/uds-common/v1.0.0/tasks/create.yaml
  - deploy: https://raw.githubusercontent.com/defenseunicorns/uds-common/v1.0.0/tasks/deploy.yaml
  - publish: https://raw.githubusercontent.com/defenseunicorns/uds-common/v1.0.0/tasks/publish.yaml
  - setup: https://raw.githubusercontent.com/defenseunicorns/uds-common/v1.0.0/tasks/setup.yaml

tasks:
  - name: build-package
    description: Build package
    actions:
      - task: create:package
      - task: create:package
        with:
          path: ./plugins
          options: "--flavor ''"

  - name: publish-package
    description: Publish the packages
    actions:
      - task: publish:package
        with:
          # x-release-please-start-version
          version: "10.0.0-uds.1"
          # x-release-please-end

  - name: publish-plugin-package
    description: Publish the plugin package
    actions:
      - task: publish:package
        with:
          # x-release-please-start-version
          version: "10.0.0-uds.1"
          # x-release-please-end
          name: mattermost-plugins
