includes:
  - dependencies: ./dependencies.yaml
  - test: ./test.yaml
  - create: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.11.2/tasks/create.yaml
  - deploy: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.11.2/tasks/deploy.yaml
  - publish: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.11.2/tasks/publish.yaml
  - setup: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.11.2/tasks/setup.yaml

tasks:
  - name: build-package
    description: Build package
    actions:
      - task: create:package
      - task: create:package
        with:
          path: ./plugins
          options: "--flavor ''"

  - name: test-package
    description: Test the package
    actions:
      - task: dependencies:create
      - task: create:test-bundle
      - task: setup:k3d-test-cluster
      - task: deploy:test-bundle
      - task: setup:create-doug-user
      - task: test:all

  - name: publish-package
    description: Publish the packages
    actions:
      - task: publish:package
        with:
          # x-release-please-start-version
          version: "9.11.1-uds.0"
          # x-release-please-end

  - name: publish-plugin-package
    description: Publish the plugin package
    actions:
      - task: publish:package
        with:
          # x-release-please-start-version
          version: "9.11.1-uds.0"
          # x-release-please-end
          name: mattermost-plugins
