variables:
  - name: TARGET_REPO
    default: oci://ghcr.io/defenseunicorns/packages/uds

  - name: VERSION
    description: The version of the package to build
    # x-release-please-start-version
    default: "9.3.0-uds.2"
    # x-release-please-end

tasks:
  - name: package
    description: Build and publish the packages
    actions:
      - description: Create the packages
        cmd: ZARF_ARCHITECTURE=amd64 uds run -f tasks/create.yaml mattermost-package --no-progress

      - description: Publish the packages
        cmd: zarf package publish zarf-package-mattermost-amd64-${VERSION}.tar.zst ${TARGET_REPO}
