tasks:
  - name: health-check
    actions:
      - description: Mattermost Health Check
        wait:
          cluster:
            kind: Deployment
            name: mattermost-enterprise-edition
            namespace: mattermost
            condition: Available

  - name: ingress
    actions:
      - description: Mattermost UI Health Check
        wait:
          network:
            protocol: https
            address: chat.uds.dev
            code: 200

  - name: smoke
    description: Mattermost Smoke Check
    actions:
      - cmd: |
          npm ci
          npx playwright install --with-deps
      - cmd: npx playwright test --project chromium firefox # webkit doesn't retry 421s so fails with login
