tasks:
  - name: all
    actions:
      - task: ingress
      - task: ui

  - name: ingress
    actions:
      - description: Mattermost UI Health Check
        wait:
          network:
            protocol: https
            address: chat.uds.dev
            code: 200

  - name: ui
    description: Mattermost UI Checks
    actions:
      - cmd: |
          docker run --rm --ipc=host --net=host --mount type=bind,source="$(pwd)",target=/app mcr.microsoft.com/playwright:v1.43.1-jammy sh -c " \
            cd app && \
            npm ci && \
            npx playwright test \
            "
        dir: tests