tasks:
  - name: health-check
    actions:
      - description: Mattermost Health Check
        wait:
          cluster:
            kind: Deployment
            name: mattermost-enterprise-edition
            namespace: mattermost
            condition: Available

  - name: ingress
    actions:
      - description: Mattermost UI Health Check
        wait:
          network:
            protocol: https
            address: chat.uds.dev
            code: 200
