tasks:
  - name: health-check
    actions:
      - description: Mattermost Exporter Health Check
        wait:
          cluster:
            kind: Deployment
            name: mattermost-mattermost-exporter
            namespace: mattermost

      - description: Mattermost Registry Health Check
        wait:
          cluster:
            kind: Deployment
            name: mattermost-registry
            namespace: mattermost

      - description: Mattermost Shell Health Check
        wait:
          cluster:
            kind: Deployment
            name: mattermost-mattermost-shell
            namespace: mattermost

      - description: Mattermost Toolbox Health Check
        wait:
          cluster:
            kind: Deployment
            name: mattermost-toolbox
            namespace: mattermost

      - description: Mattermost Sidekiq Health Check
        wait:
          cluster:
            kind: Deployment
            name: mattermost-sidekiq-all-in-1-v2
            namespace: mattermost

      - description: Mattermost Webservice Health Check
        wait:
          cluster:
            kind: Deployment
            name: mattermost-webservice-default
            namespace: mattermost

      - description: Mattermost Gitaly Health Check
        wait:
          cluster:
            kind: StatefulSet
            name: mattermost-gitaly
            namespace: mattermost

      - description: Mattermost Migrations Health Check
        wait:
          cluster:
            kind: Job
            name: mattermost-migrations-1
            namespace: mattermost

  - name: ingress
    actions:
      - description: Mattermost UI Health Check
        wait:
          network:
            protocol: https
            address: mattermost.uds.dev
            code: 200
