tasks:
  - name: ingress
    actions:
      - description: Mattermost UI Health Check
        wait:
          network:
            protocol: https
            address: mattermost.uds.dev
            code: 200
