tasks:
  - name: all
    actions:
      - task: health-check
      - task: ingress
      - task: ui

  - name: health-check
    actions:
      - description: Mattermost Health Check
        wait:
          cluster:
            kind: Deployment
            name: mattermost-enterprise-edition
            namespace: mattermost
            condition: Available

  - name: ingress
    actions:
      - description: Mattermost UI Health Check
        wait:
          network:
            protocol: https
            address: chat.uds.dev
            code: 200

  - name: ui
    description: Mattermost UI Checks
    maxTotalSeconds: 600
    actions:
      - cmd: npm ci
        dir: tests
      - cmd: npx playwright install --with-deps
        dir: tests
      - cmd: npx playwright test
        dir: tests
