apiVersion: v1
kind: Secret
metadata:
  name: mattermost-sso
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MM_GITLABSETTINGS_ENABLE: "{{ .Values.sso.enabled | toString }}"
  MM_GITLABSETTINGS_ID: "{{ .Values.sso.client_id }}"
{{- if .Values.sso.enabled }}
  MM_GITLABSETTINGS_SECRET: "{{ (lookup "v1" "Secret" "mattermost" "sso-client-uds-core-mattermost").data.secret | b64dec }}"
{{- else }}
  MM_GITLABSETTINGS_SECRET: ""
{{- end }}
  MM_GITLABSETTINGS_AUTHENDPOINT: "https://sso.{{ .Values.domain }}/oauth/authorize"
  MM_GITLABSETTINGS_TOKENENDPOINT: "https://sso.{{ .Values.domain }}/oauth/token"
  MM_GITLABSETTINGS_USERAPIENDPOINT: "https://sso.{{ .Values.domain }}/api/v4/user"
  MM_EMAILSETTINGS_ENABLESIGNUPWITHEMAIL: "{{ .Values.sso.enable_sign_up_with_email | toString }}"
  MM_EMAILSETTINGS_ENABLESIGNINWITHEMAIL: "{{ .Values.sso.enable_sign_in_with_email | toString }}"
  MM_EMAILSETTINGS_ENABLESIGNINWITHUSERNAME: "{{ .Values.sso.enable_sign_in_with_username | toString }}"
