variables:
  dev-minio:
    buckets: |
      - name: uds-mattermost-dev
  postgres-operator:
    postgresql:
      enabled: true  # Set to false to not create the PostgreSQL resource
      teamId: "uds"
      volume:
        size: "10Gi"
      numberOfInstances: 2
      users:
        mattermost.mattermost: []  # database owner
      databases:
        mattermost: mattermost.mattermost
      version: "13"
      ingress:
        remoteGenerated: Anywhere