domain: "###ZARF_VAR_DOMAIN###"
sso:
  oidc: 
    enabled: true
objectStorage:
  secure: true
  accessKey: ""
  secretKey: ""
  bucket: "mattermost"
  endpoint: "s3.amazonaws.com"
  region: "us-west-1"

postgres:
  username: "mattermost"
  password: ""
  host: ""
  port: 5432
  dbName: "mattermost"
  # Example: "?connect_timeout=10&sslmode=disable"
  connectionOptions: ""

# The subdomain for the mattermost server, will be prefixed to your domain (ex: mattermost.example.com)
subdomain: "chat"

# Additional configuration for Mattermost
config:
  enablePluginUploads: false
