# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: CI Doc Shim

on:
  pull_request:
    branches: [main]
    types: [milestoned, opened, synchronize]

jobs:
  validate:
    strategy:
      matrix:
        type: [install, upgrade]
        flavor: [upstream, registry1, unicorn]
    uses: defenseunicorns/uds-common/.github/workflows/callable-ci-docs-shim.yaml@f0164622ffc2007e96a0e1deaa3f5064db04b148 # v1.1.0
    with:
      flavor: ${{ matrix.flavor }}
      type: ${{ matrix.type }}
    secrets: inherit # Inherits all secrets from the parent workflow.
