name: CI Docs Shim

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - '.github/**'
      - 'bundle/**'
      - 'values/**'
      - 'tasks/**'
      - 'tests/**'
      - 'tasks.yaml'
      - 'zarf.yaml'

jobs:
  test:
    runs-on: "ubuntu-latest"
    timeout-minutes: 20
    name: Deploy ${{ matrix.flavor }}
    strategy:
      matrix:
        flavor: [upstream, registry1]
    steps:
      - name: Shim for Deploy ${{ matrix.flavor }}
        run: |
          echo "Documentation-only change detected; marking Deploy ${{ matrix.flavor }} as successful."
