name: Test the Mattermost Package on arm64 with qemu

on:
  push:
    branches:
      - ewyles/test-qemu

permissions:
  contents: read

jobs:
  test-qemu:
    runs-on: uds-ubuntu-arm64-4-core
    name: Test QEMU ${{ matrix.flavor }} ${{ matrix.architecture }}

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Environment setup
        uses: defenseunicorns/uds-common/.github/actions/setup@4cea6c8858b9f4db3a3624a6fc046db77e1f4eaa # v0.5.0
        with:
          registry1Username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          registry1Password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}
          ghToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Test Package
        run: UDS_ARCHITECTURE=arm64 uds run test-package --set FLAVOR=upstream

      - name: Debug Output
        if: ${{ always() }}
        uses: defenseunicorns/uds-common/.github/actions/debug-output@4cea6c8858b9f4db3a3624a6fc046db77e1f4eaa # v0.5.0

      - name: Save logs
        if: always()
        uses: defenseunicorns/uds-common/.github/actions/save-logs@4cea6c8858b9f4db3a3624a6fc046db77e1f4eaa # v0.5.0
        with:
          suffix: ${{ matrix.flavor }}-${{ matrix.architecture }}-${{ github.run_id }}-${{ github.run_attempt }}
