# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Release

on:
  push:
    branches:
      - main

# Permissions for the GITHUB_TOKEN used by the workflow.
permissions:
  contents: read # Allows reading the content of the repository.
  packages: read # Allows reading the content of the repository's packages.
  id-token: write

jobs:
  tag-new-version:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-flag.outputs.release_created }}
    steps:
      - name: Create Release Tag
        id: tag
        uses: googleapis/release-please-action@d1a8f221d7723166f48a584aebba00ef3f6febec # v4.1.4
      - id: release-flag
        run: echo "release_created=${{ steps.tag.outputs.release_created || false }}" >> "$GITHUB_OUTPUT"

  publish:
    permissions:
      contents: write # Allows writing the content of the repository.
      packages: write # Allows writing the content of the repository's packages.
      id-token: write
    needs: tag-new-version
    if: ${{ needs.tag-new-version.outputs.release_created == 'true' }}
    strategy:
      matrix:
        flavor: [upstream, registry1, unicorn]
        architecture: [amd64, arm64]
        exclude:
          - flavor: registry1
            architecture: arm64
    uses: defenseunicorns/uds-common/.github/workflows/callable-publish.yaml@3d35c13d5a99b107de55cea6447dbce91884433d # v1.10.0
    with:
      flavor: ${{ matrix.flavor }}
      runsOn: ${{ matrix.architecture == 'arm64' && 'uds-swf-ubuntu-arm64-8-core' || 'uds-swf-ubuntu-big-boy-8-core' }}
      reports-path: "tests/.playwright/reports/"
    secrets: inherit # Inherits all secrets from the parent workflow.
