name: Test

# This workflow is triggered on pull requests to the main branch.
on:
  pull_request:
    paths:
      - ".github/**"
      - "bundle/**"
      - "values/**"
      - "tasks/**"
      - "tests/**"
      - "tasks.yaml"
      - "zarf.yaml"

# Abort prior jobs in the same workflow / PR
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    uses: defenseunicorns/uds-common/.github/workflows/shared-test-deploy.yaml@17-ewyles-workflow-consolidation
    with:
      flavors: '"upstream", "registry1"'
      runson: '"ubuntu-latest"'
    secrets: inherit
