name: Test

# This workflow is triggered on pull requests to the main branch.
on:
  pull_request:
    paths:
      - ".github/**"
      - "bundle/**"
      - "values/**"
      - "tasks/**"
      - "tests/**"
      - "tasks.yaml"
      - "zarf.yaml"

# Abort prior jobs in the same workflow / PR
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run-test:
    name: Create and Deploy Flavor ${{ matrix.flavor }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        flavor: [upstream, registry1]

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Environment setup
        uses: defenseunicorns/uds-common/.github/actions/setup@17-ewyles-workflow-consolidation
        with:
          username: ${{secrets.IRON_BANK_ROBOT_USERNAME}}
          password: ${{secrets.IRON_BANK_ROBOT_PASSWORD}}

      - name: Test
        uses: defenseunicorns/uds-common/.github/actions/test@17-ewyles-workflow-consolidation
        with:
          flavor: ${{ matrix.flavor }}

      - name: Save logs
        if: always()
        uses: defenseunicorns/uds-common/.github/actions/save-logs@417b9c2bc088f664c616c9929a2b3ce448d251f7
        with:
          suffix: ${{ matrix.flavor }}-${{ github.run_id }}-${{ github.run_attempt }}
